### ISSUE TITLE
request addition: De Libro Medicinali

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#10]
Our correspondent (via paper mail) asks that his translation be cataloged:
http://books.google.com/books/about/De_Libro_Medicinali_Quinti_Sereni_Sammon.html?id=LDDAGwAACAAJ

http://tufts.worldcat.org/title/de-libro-medicinali-quinti-sereni-sammonici/oclc/55872695&referer=brief_results

**Comment by AlisonBabeu** [comment]
This record is now live in the catalog http://catalog.perseus.org/catalog/urn:cts:latinLit:phi1515.phi001.opp-eng1 so I'm closing this issue.

**Comment by lcerrato** [comment]
Great. Now I have to remember to send him a letter!
