### ISSUE TITLE
viaf59475586.mads.xml is also mal-formed

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#104]
'''
$ xmllint viaf59475586.mads.xml
viaf59475586.mads.xml:38: parser error : Opening and ending tag mismatch: url line 25 and mads
</mads:mads>
            ^
viaf59475586.mads.xml:39: parser error : Premature end of data in tag url line 25

^
viaf59475586.mads.xml:39: parser error : Premature end of data in tag mads line 2

^
'''

**Comment by AlisonBabeu** [comment]
Fixed this error too.

**Comment by cwulfman** [comment]
Thanks! I'm ingesting the records into an xml database to explore them a bit; there may be more glitches.
