### ISSUE TITLE
mods records not parsing

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#108]
[malformed.txt](https://github.com/PerseusDL/catalog_data/files/1411377/malformed.txt)

**Comment by AlisonBabeu** [comment]
So @cwulfman I've updated all these files and they are now showing up as valid within my Oxygen. Same goes for the other random MODS and MADS file issues from before. I hope this is everything (but I"m sure its not!) :)

**Comment by cwulfman** [comment]
Looks good — I closed all the tickets. Thanks for doing this!

On Oct 25, 2017, at 10:29 AM, Alison Babeu <notifications@github.com<mailto:notifications@github.com>> wrote:


So @cwulfman<https://github.com/cwulfman> I've updated all these files and they are now showing up as valid within my Oxygen. Same goes for the other random MODS and MADS file issues from before. I hope this is everything (but I"m sure its not!) :)
