### ISSUE TITLE
new edition-level MODS file for Thucydides Epidoc version

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#11]
We need a new edition-level MODS file for the Epidoc version of Thucydides Histories, which is based on urn:cts:greekLit:tlg0003.tlg001.perseus-grc1

(Like issue #9 for Athenaeus)

**Comment by AlisonBabeu** [comment]
As this edition now has a permanent catalog record (http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0003.tlg001.perseus-grc2), I'm closing this issue.
