### ISSUE TITLE
What is the function of textgroups?

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#112]
There are 4,306 text groups in the textgroups cite table. While some appear to refer to actual groups of texts (e.g., Scholia in Thucydidem), almost all appear to be named after authors. What do these textgroups actually do?

And how to they correspond to the textgroups in the CTS scheme? Are those itemized and/or described anywhere?

**Comment by AlisonBabeu** [comment]
They slice, they dice, they are the amazing Perseus textgroups.

But seriously, textgroups are a key part of the CTS architecture that are essentially defined by the protocol as "traditional, convenient groupings of texts such as ‘authors’ for literary works, or corpus collections for epigraphic or papyrological texts” and include unique identifiers but also support multiple titles (to support multi-lingual collections).".  

We have made use of textgroups as a concept not only to support the CTS architecture within the MODS and MADS catalog records , but also to be able to encompass unique authorital identities and more importantly identifiers for not only extant authors [(Homer](http://catalog.perseus.org/catalog/urn:cite:perseus:author.745), but also for more loosely defined "authors" or pseudo-authors ([Pseudo Caesar](http://catalog.perseus.org/catalog/urn:cite:perseus:author.1192), groups of authors ([Scriptores Historiae Augustae](http://catalog.perseus.org/catalog/urn:cite:perseus:author.1743)),  or what in cataloging, might be described as uniform titles such as the [Homeric Hymns](http://catalog.perseus.org/catalog/urn:cite:perseus:author.1738)

Textgroups have allowed us to assign a high level label and unique identifier to all of the identified works in the Perseus Catalog and to aggregate them, at least, that is always how I've seen and defined their purpose. Our use of textgroups corresponds pretty closely to the CTS definition, with some tweaks, here and there.

**Comment by cwulfman** [comment]
That's what I thought. Thanks!
