### ISSUE TITLE
MADS records (authors) without citeurns

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#113]
The attached xml document contains the mads:authority part of mads records that do not have a <mads:identifier type='citeurn'> element (you should be able to figure out which file contains the document from the namePart, right?)

At least one of these (nilus.mads.xml) is invalid, because it doesn't include the mads: namespace on the identifier element (i.e., it is <identifier type='citeurn'> rather than <mads:identifier type='citeurn'>). Perhaps that will be the case will all of them?

[mads-without-citeurns.xml.zip](https://github.com/PerseusDL/catalog_data/files/1511623/mads-without-citeurns.xml.zip)

**Comment by cwulfman** [comment]
An update: there are 4,284 invalid identifiers. I'll clean these up first.

**Comment by cwulfman** [comment]
I cleaned up the invalid identifiers and reduced the number of records without <mads:identifier type='citeurn'> elements to 20.  Updated list attached.

[mads-without-citeurns.xml.zip](https://github.com/PerseusDL/catalog_data/files/1511771/mads-without-citeurns.xml.zip)

**Comment by AlisonBabeu** [comment]
Thanks for doing this.  I've started looking at the records and there seem to be a few things going on.  I should post more tomorrow.

**Comment by AlisonBabeu** [comment]
So after going through this list, I've found two authority record errors to fix, one or two that don't make any sense for not having citeurns, but the majority of the list (17 of the 20) are records for fragmentary historians who did not have TLGs, so we created a semantic textgroup of FHG, to support the creation of CTS URNs for these authors. Thanks for this list @cwulfman I will  add the missing CITE URNs for this small group of records.

**Comment by cwulfman** [comment]
Thanks, Alison!

**Comment by AlisonBabeu** [comment]
Hi @cwulfman I added in CITE URNs to all these records so I'm going to close this because I'm pretty sure that settles the issue.
