### ISSUE TITLE
multiple MADS records with same citeurn

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#119]
Not nearly as many of these as in the MODS case!

"urn:cite:perseus:author.1172.1"
L/Leocrines_Historicus/leocrinus.mads.xml
P/Posidippus/nr97-44893.xml.mads.xml

"urn:cite:perseus:author.1656.1"
J/Justas_Tiberias/n79077601.madsxml.xml
P/Pausanias_Lacon/viaf27455714.mads.xml

"urn:cite:perseus:author.516.1"
D/Diophanes_of_Myrina/DiophanesMyrinus.mads.xml
M/Myrinus_Epigrammaticus/Myrinus.mads.xml

"urn:cite:perseus:author.194.1"
A/Archinus_Historicus/viaf57001292.mads.xml
A/Aristodemus_Historicus/viaf76705877.mads.xml

These citeurns appear nowhere in the MODS data. Is it ok if I simply change them?

**Comment by AlisonBabeu** [comment]
Having looked into a few of these records I think something most have gone wrong with a previous update. In several cases there are authors who somehow had an authority record CITE URN assigned to another author as well.

1) Leocrinus is a minor fragmentary historian  with one work record, whereas Posidipppus has multiple records in catalog_data, including an authority record, but for some reason the Perseus Catalog now has his textgroup as the CITE URN, and has lost the link to the authority record. Should we add the CITE URN that is the Perseus Catalog proper to the CITE TABLEs record?

2) The record for Justas Tiberias does not show up, like the record for Pausanias in the CITE Collections table at all, despite its presence in catalog_data I wonder if this happened when for some reason the CITE ID was overwritten.

3) There are two different CITE URNs in the CITE Collection tables, for Diophanes Myrinus and Myrinus, so I updated them.

4) I've fixed the problem with the TLG ID that causes the fourth problem, I think you can simply change the ID for Aristodemus Historicus if that works, as the CITE ID does appear in both catalog_data and the MADS record for Archinus.

**Comment by cwulfman** [comment]
Thanks, Alison -- Here's what I did in addition:

**"urn:cite:perseus:author.1172.1"**
L/Leocrines_Historicus/leocrinus.mads.xml
P/Posidippus/nr97-44893.xml.mads.xml -> 2012.1

**"urn:cite:perseus:author.1656.1"**
J/Justas_Tiberias/n79077601.madsxml.xml
P/Pausanias_Lacon/viaf27455714.mads.xml -> 2013.1

**"urn:cite:perseus:author.194.1"**
A/Archinus_Historicus/viaf57001292.mads.xml
A/Aristodemus_Historicus/viaf76705877.mads.xml -> 2014.1
