### ISSUE TITLE
new edition-level MODS file for Gulick Athenaeus Deip.

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#12]
We need a new edition-level MODS file for the Epidoc version of the Athenaeus GULICK edition. This digital edition will be derived from the current P4 version http://data.perseus.org/texts/urn:cts:greekLit:tlg0008.tlg001.perseus-grc1

**Comment by AlisonBabeu** [comment]
This edition is now available in the catalog (http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0008.tlg001.perseus-grc4) so I'm closing this issue.
