### ISSUE TITLE
two records for Titus Ampius Balbus

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#120]
mads/PrimaryAuthors/A/Ampius Balbus, Titus/ : citeurn = urn:cite:perseus:author.82.1
mads/PrimaryAuthors/B/Balbus, T. Ampius .     : citeurn = urn:cite:perseus:author.260.1

The descriptions suggest both records refer to the same person.

**Comment by AlisonBabeu** [comment]
You are quite right @cwulfman, this second one is a duplicate, so I"m going to delete it and redirect its URN.
