### ISSUE TITLE
new translation-level MODS file for Athenaeus - Yonge translation

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#13]
We need a new edition-level MODS file for the Epidoc version of the Athenaeus Yonge translation. This digital edition is derived from the current P4 version http://data.perseus.org/texts/urn:cts:greekLit:tlg0008.tlg001.perseus-eng1

**Comment by AlisonBabeu** [comment]
There is a permanent catalog record for this edition (http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0008.tlg001.perseus-eng2) so I am closing this issue.
