### ISSUE TITLE
WorldCat Entities?

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#131]
@AlisonBabeu what do you know about this effort: https://www.oclc.org/developer/develop/linked-data/worldcat-entities.en.html

**Comment by AlisonBabeu** [comment]
This is the first I have seen of it though I have followed many of OCLC's other linked data and FRBR research projects.

**Comment by cwulfman** [comment]
Here's a table that relates cts urns, their associated worldcat urls (from the MODS records), and the associated worldcat/work entities.
[oclcworks.csv.zip](https://github.com/PerseusDL/catalog_data/files/1670431/oclcworks.csv.zip)
