### ISSUE TITLE
duplicate fieldOfActivity elements in some MADS records

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#132]
@AlisonBabeu wrote in an email:

> when I clicked on the list of Agricultural Author (http://174.138.78.35:8080/exist/apps/PerseusCatalog/browse.html?activity=Agricultural%20Author), I found two author names duplicated there, Siculus Flaccus and Hyginus Gromaticus, so Siculus and Hyginus are both listed twice.

This appears to be because ```  <mads:fieldOfActivity>Agricultural author</mads:fieldOfActivity>``` appears twice. This may be a side-effect of the recent consolidation of terms.

I'll fix.

**Comment by cwulfman** [comment]
Fixed in ce3ae647ba2c27dd6ba3ce71e4e9b57e0999575e
@AlisonBabeu please check, and then close ticket if all looks well.

**Comment by AlisonBabeu** [comment]
This looks good, just one last request.
Can we merge  logoographer into logographer. Gotta love my typos.

**Comment by cwulfman** [comment]
Done!
