### ISSUE TITLE
Encoding of Fragmenta historicorum graecorum?

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#139]
Has this been done? I'd like to try to harvest ids for all the fragments.

**Comment by AlisonBabeu** [comment]
Monica's DFHG project has created TEI XML encoded versions of all the files.  Links to all of them can be found here: https://dfhg-project.github.io/

**Comment by cwulfman** [comment]
I thought I remembered that!
What is the relationship between the fragments (with IDs) in the FHG and the 880 MODS records in catalog_data with the FHG as a host?

**Comment by AlisonBabeu** [comment]
Its complicated. Perhaps to be discussed during our hangout?
