### ISSUE TITLE
(stoa0023.stoa001) title change

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#166]
This is usually referred to just as Res Gestae in nominative rather than the genitive (which makes sense only if you use Rerum Gestarum Libri Qui Supersunt — which is uncommon.)

**Comment by lcerrato** [comment]
see also https://github.com/PerseusDL/canonical-latinLit/pull/290

**Comment by AlisonBabeu** [comment]
Hi @lcerrato so I changed the uniform title in the CITE Collections table and also changed all the relevant uniform titles for the records in the revised catalog_data set I'm working. Thanks for catching this.
