### ISSUE TITLE
(urn:cite:perseus:catver.13078.1) weird duplicates in release

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#168]
Looks like when we bumped four files simultaneously for training that the data was overwritten

http://catalog.perseus.org/cite-collections/versions/search?utf8=✓&field_type=urn&search=13078.1

I will try to manually edit this by adding a letter and changing the data.

**Comment by lcerrato** [comment]
@AlisonBabeu 
Could you take a look at the above link and see if what I did makes sense? Looks like the data is all different now and looks like versions.xml.
Do we want to manually change versions.xml?

**Comment by AlisonBabeu** [comment]
@lcerrato this looks ok, and the metadata revisions seem correct. I think it is probably a good idea to change versions.xml manually as well, I can do that if you like!

**Comment by lcerrato** [comment]
@AlisonBabeu 
Great. I tweaked the title on stoa0023 (I think there was another issue on this). Also, none of those entries had the referring base urn (what the record was bumped from), so I added that.

**Comment by lcerrato** [comment]
http://catalog.perseus.org/cite-collections/versions/urn:cite:perseus:catver.13078.1a
http://catalog.perseus.org/cite-collections/versions/urn:cite:perseus:catver.13078.1b
http://catalog.perseus.org/cite-collections/versions/urn:cite:perseus:catver.13078.1c
http://catalog.perseus.org/cite-collections/versions/urn:cite:perseus:catver.13078.1d

**Comment by lcerrato** [comment]
fixed
