### ISSUE TITLE
(stoa0023.stoa001) trying to bump eng URN

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#169]
It looks like different parts of this work got additional IDs.
I would like to just bump the English translation to perseus-eng2 but there is already a eng2, eng3, eng4.

Can/should those be deleted from the CITE collections?

**Comment by AlisonBabeu** [comment]
I think in order to be more consistent with CTS and to move away from using IDs like this for parts of a work, we should definitely change these CTS-URNs.  I can't actually delete any versions from the online tables only redirect them. I can delete and update in the XML file that lives on catalog_data however @lcerrato

**Comment by lcerrato** [comment]
Ok — I want to do what makes the most sense for now without causing a cascade of issues down the line. 
Maybe change to 0002a, 0002b, 0002c at some point?
Should I use eng2 or just go to the next available? (eng5, I think)?
What's weird is that there is some running intro text in this main file already. So I think it's already inconsistent.

**Comment by AlisonBabeu** [comment]
Perhaps we could change the eng2 eng3 and eng4 to to 001a-eng1, 001b--eng1 and 001c-eng1. The whole problem too is that these are all introductions to the same work, this division is just based on Volume 1, 2, and 3. If we create at stoa0023.stoa002 it implies there is a second work by Ammianus Marcellinus unless I am misreading you. I think stoa0023.stoa002.perseus-eng2 should definitely be reserved for a bumped version of the work. Am I making sense?

**Comment by lcerrato** [comment]
I was unclear above. Trying to do too many things at once with this file.
I meant to add the letter to the work ID number so that my new file is 
stoa0023.stoa001.perseus-eng2 (as opposed to whatever supplemental material is using eng2 now.

**Comment by AlisonBabeu** [comment]
Gotcha. Yes, definitely reserve the URN stoa0023.stoa001.perseus-eng2  for the bumped version of this work and we should put our heads together to figure out how we want to do the other urns moving forward. I'm pretty sure there are a number of other Perseus English translations that may have similar issues.

**Comment by lcerrato** [comment]
Ok! fixed others in the cite collections and bumped the English to eng2
