### ISSUE TITLE
new MODS files needed for Aristophanes

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#17]
In response to request from Greg and Monica Berti I'm putting Epidoc versions of Aristophanes into Perseids and we need new CTS urns for the Epidoc editions and translations.

The epidoc versions will be based upon the following

Birds tlg0019.tlg006.perseus-grc1 & tlg0019.tlg006.perseus-eng1
Clouds tlg0019.tlg003.perseus-grc1 & tlg0019.tlg003.perseus-eng1
Ecclesiazusae tlg0019.tlg010.perseus-grc1 & tlg0019.tlg010.perseus-eng1
Lysistrata tlg0019.tlg007.perseus-grc1 & tlg0019.tlg007.perseus-eng1

**Comment by AlisonBabeu** [comment]
The extra Latin files have been deleted and all of the Aristophanes Epidoc editions now have MODS records so I'm closing this issue.
