### ISSUE TITLE
(tlg0007.tlg079.perseus-eng2 and 4) translator name

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#171]
this was eng2 and has been bumped to eng 4

It looks like the translator is Davis rather than Davies?
http://www.archive.org/stream/plutarchsmoralst02plutuoft#page/n7/mode/2up

**Comment by AlisonBabeu** [comment]
Yes it does and this Davis has no authority record unfortunately. I will go fix that in the source edition record.
