### ISSUE TITLE
(tlg0007.tlg094.perseus-eng2) translator name?

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#175]
Hi @AlisonBabeu 
In the book I see "C.H."
http://www.archive.org/stream/plutarchsmoralst03plutuoft#page/x/mode/2up
 but the catalog has Matthew Morgan. http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0007.tlg094.perseus-eng2

If it is C.H., is there a way to identify him?

**Comment by AlisonBabeu** [comment]
And to think I once though that the Goodwin Plutarch Moralia were on of the better cataloged collections. Sigh. I will do some digging and see if I can identify this translator. Thanks for catching this.
