### ISSUE TITLE
(tlg0007.tlg098.perseus-eng2) information

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#177]
Here 
http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0007.tlg098.perseus-eng2
It looks like the title should be 
Of Natural Affection Towards One's Children
translated by R. Brown.

(see http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0007.tlg098.opp-eng1)

**Comment by AlisonBabeu** [comment]
You are quite corrected and I fixed it in (https://github.com/PerseusDL/catalog_data/commit/6fd125f4506c64ae647611d537bf83a4b8031ea4) but I accidentally closed the wrong issue.  Off to fix that one now.

**Comment by lcerrato** [comment]
@AlisonBabeu 
Is the translator correct?

**Comment by lcerrato** [comment]
https://books.google.com/books?id=ab8pAAAAYAAJ&pg=PA187&dq=Of+natural+affection+towards+one%27s+offspring+Richard+Brown&hl=en&sa=X&ved=0ahUKEwj0gsmw27njAhUmVt8KHXVoCEcQ6AEINTAC#v=onepage&q=Of%20natural%20affection%20towards%20one's%20offspring%20Richard%20Brown&f=false

**Comment by AlisonBabeu** [comment]
I fixed this with https://github.com/PerseusDL/catalog_data/commit/3c79ad384cc84d7fdb98feada465ebc7a64e5da4.
