### ISSUE TITLE
(tlg0007.tlg130.perseus-eng2) incorrect translator?

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#181]
http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0007.tlg130.opp-eng1 has the translator as A.J. (or "Sir" A.J., if you prefer) but 
http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0007.tlg130.perseus-eng2
has Baxter

**Comment by AlisonBabeu** [comment]
You know I really was joking about the late afternoon Plutarch issue, but I'll take care of this soon!

**Comment by lcerrato** [comment]
I cannot disappoint!
