### ISSUE TITLE
(tlg0019.tlg007.perseus-eng1) updated info

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#184]
Hi @AlisonBabeu 
I think I mentioned this when we had an email on it a while back. I also bought the book, I think, at that time. Who knows these days. 
First, I'm not sure why it was bumped, but it was. Maybe before we knew it was restricted?

I think it is this edition http://www.worldcat.org/oclc/841600732

**Comment by AlisonBabeu** [comment]
That definitely looks like it could be an the edition for this work and I"m not sure why it was bumped either.  Would you recommend using this edition as a basis for the catalog metadata?

**Comment by lcerrato** [comment]
yes, I think I checked this previously, so go for it!

**Comment by AlisonBabeu** [comment]
I've update the catalog record to include this metadata so I'm closing this issue!
