### ISSUE TITLE
new MODS file needed for Aeschylus Prometheus Bound

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#19]
We need a new MODS file for the Epidoc edition of Prometheus Bound, which is based on urn:cts:greekLit:tlg0085.tlg003.perseus-grc1.  Simona Stoyanova did the epidoc conversion.

**Comment by AlisonBabeu** [comment]
The incorrect translation file has been deleted and the Epidoc edition is now present in the catalog so I'm closing this issue.
