### ISSUE TITLE
(tlg099.tlg001.perseus-eng2) incorrect source info?

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#195]
Working on this file and it is listed as Bell edition with later dates, but I think it was first a Bohn edition with earlier dates. The earlier ones are the only ones I see online.
https://archive.org/details/geographyofstrab01strarich/geographyofstrab01strarich/page/n13/mode/2up  vol_1 Books 1-7 
https://archive.org/details/geographyofstrab02strarich/geographyofstrab02strarich/page/n7/mode/2up vol_2 Books 8-13 
https://archive.org/details/b24872556_0003/page/n3/mode/2up vol_3 Books 14-17

**Comment by lcerrato** [comment]
Never mind found the 1889 edition reprint.

**Comment by AlisonBabeu** [comment]
@lcerrato that is what I call effiiciency, you closed the issue before I could even comment! :)
