### ISSUE TITLE
new MODS file for Statius, Thebaid

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#22]
We need a new catalog entry for the Epidoc edition of urn:cts:latinLit:phi1020.phi001.perseus-lat1 
(see related request https://github.com/PerseusDL/perseids_docs/issues/186 )

**Comment by AlisonBabeu** [comment]
I have deleted the English language file that was incorrectly generated and there is now a record for this edition in the catalog so I'm closing this issue.
