### ISSUE TITLE
New MODS file for Valerius Flaccus, Argonautica

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#24]
We need a new catalog entry for the Epidoc edition of urn:cts:latinLit:phi1035.phi001.perseus-lat1
(see related request PerseusDL/perseids_docs#186 )

**Comment by AlisonBabeu** [comment]
This file has made it into catalog_data but does not appear in the catalog as yet, due to the double CTS-URN issue that we are still investigating. https://github.com/PerseusDL/catalog_data/blob/master/mods/latinLit/phi1035/phi001/perseus-lat2/phi1035.phi001.perseus-lat2.mods1.xml

**Comment by AlisonBabeu** [comment]
This file is now live in the catalog, http://catalog.perseus.org/catalog/urn:cts:latinLit:phi1035.phi001.perseus-lat2, so I'm closing this issue.
