### ISSUE TITLE
Issue with Aulus Licinius Archias

### ISSUE THREAD

**Issue by annakrohn** [PerseusDL/catalog_data#26]
There appears to be something odd with Aulus Licinius Archias.  He seems to have two MADS records one under PrimaryAuthors/A/Archias/n84-234520.xml.mads.xml and another PrimaryAuthors/A/Aulus Licinius Archias, 5th Cent B.C/AulusLiciniusArchias.mads.xml.

The alt names in the second record (AulusLiciniusArchias.mads.xml) are for Zeuxis, Heracleensis , 5. Jh. v. Chr. who seems to have been a painter?

Is this an odd duplicate case?

**Comment by AlisonBabeu** [comment]
These authors are not duplicates and I have added a few explanatory notes to the authority records to avoid confusion, so I'm closing this issue.
