### ISSUE TITLE
Catalog Display Wishlist

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/catalog_data#27]
Per conversation with Anna, this issue is being created to list several areas where the data in the catalog records (ATOM) is not being displayed or indexed, when such data might be useful. 

1) Add support for the display of pages that were encoded as lists, for example in record
http://data.perseus.org/catalog/urn:cts:greekLit:tlg0126.tlg001.opp-grc2/atom, there were epigrams on multiple pages, and so was thus encoded as 
<mods:extent unit="pages">
<mods:list>156-157, 174-175</mods:list>
</mods:extent>

2) Add the abbreviated titles into the expression level record and possibly make them searchable/indexable, this would be particularly useful in terms of the epigrammatists and fragmentary authors. For example, in the above record, the following information was included

<mods:titleInfo type="abbreviated">
<mods:title>AG 5.58, AG 5.59, AG 5.98</mods:title>
</mods:titleInfo>
<mods:titleInfo type="abbreviated">
<mods:title>AP 5.58, AP 5.59, AP 5.98</mods:title>
</mods:titleInfo>

And for the fragmentary historians, further information was also included in the displayLabel attribute,
for example in record, http://data.perseus.org/catalog/urn:cts:greekLit:tlg0116.tlg002/atom:

<mods:titleInfo type="abbreviated" displayLabel="FHG">
<mods:title>FHG 4: 279-284</mods:title>
</mods:titleInfo>
<mods:titleInfo type="abbreviated" displayLabel="FGrH">
<mods:title>FGrH 685</mods:title>
</mods:titleInfo>
As a side note, some fragmentary historians had these titles included in the work title, it seems this data may have been drawn in from the Authors-Abbreviations-Editions spreadsheet, but is uneven.

3) Add in the TOC, which often have very granular information, although unfortunately only as textual strings. For example, the record for the Fragmenta of Aeschylous in Nauck's TGF, http://data.perseus.org/catalog/urn:cts:greekLit:tlg0085.tlg011.opp-grc1/atom has very detailed TOC that was not included and might be useful to display
<mods:tableOfContents>Athamas (pg. 1-4) -- Aiguptioi (pg. 4) -- Aitnaiai (pg. 4-6) -- Alkmene (pg. 6)
        -- Amumone (pg. 6-7) -- Apgeioi (pg. 7-8) -- Argo (pg. 8-9) -- Atalanth (pg. 9) -- Bakchai
        (pg. 9) -- Bassarai (pg. 9-10) -- Glaukoi (pg. 10) -- Glaukos Pontios (pg. 11-13) -- Glaukos
        Pontnieus (pg. 13-15) -- Danaides (pg. 15-17) -- Dionusou Trophoi (pg. 17-18) -- Hektoros
        Lutra v. Phruges Eleusinioi (pg. 18-19) -- Europe v. Kares Hedonoi (pg. 19-23) -- Heliades
        (pg. 23-25) -- Herakleidai (pg. 25-26) -- Thalamopoioi (pg. 26) -- Theoroi E Isthmiastai
        (pg. 26-27) -- Thrissai (pg. 27-28) -- Iereiai (pg. 28-29) -- Ixion (pg. 29-30) --
        Isthmiastai v. Theroi Iphigeneia (pg. 31) -- Kaberoi (pg. 31-32) -- Kallisto (pg. 32) --
        Kares E Europe (pg. 32-35) -- Kerkuoh Saturikos (pg. 35-36) -- Kerukes Saturoi (pg. 36-37)
        -- Kirke Saturike (pg. 37-38) -- Kressai (pg. 38-39) -- Leon Saturikos (pg. 40) -- Lemnioi
        (pg. 40) -- Lukourgos Saturikos (pg. 40-41) -- Lutra v Phruges Memnon (pg. 41-42) --
        Murmidones (pg. 42-47) -- Musoi (pg. 47-48) -- Neaniskoi (pg. 48-49) -- Nemea (pg. 49) --
        Nereides (pg. 49-50) -- Niobe (pg. 50-55) -- Xantriai (pg. 55-56) -- Oidipous (pg. 57) --
        Oplon Krisis (pg. 57-58) -- Ostologoi (pg. 58-59) -- Palamedes (pg. 59-60) -- Pentheus (pg.
        60-61) -- Perraibides (pg. 61) -- Penelope (pg. 61-62) -- Poludektes (pg. 62) -- Promethes
        (pg. 62-63) -- Prometheus Luomenos (pg. 63-68) -- Prometheus Purkaeus (pg. 68-69) --
        Prometheus Purphoros (pg. 69-70) -- Proteus Saturikos (pg. 70-72) -- Salaminiai (pg. 72-73)
        -- Semele E Hyrophoroi (pg. 73-74) -- Sisuphos Drapetes et Petrokuliestes (pg. 74-76) --
        Sphigx Saturike (pg. 76) -- Tedephos (pg. 76-77) -- Toxotides (pg. 77-79) -- Trophoi v.
        Dionusos Trophoi Upsipule (pg. 79) -- Philoktetes (pg. 79-83) -- Phorkides (pg. 83) --
        Phruges E Hektoros Lutra (pg. 84-87) -- Phrugioi (pg. 87) -- Psuchagogoi (pg. 87-88) --
        Psuchostasia (pg. 88-89) -- Oreithuia (pg. 89) -- Incertarum Fabularum Fragmenta (pg.
        90-124) -- Fragmenta Dubia et Spuria (pg. 125-128) </mods:tableOfContents>

**Comment by AlisonBabeu** [comment]
Having reviewed this, it appears that both lists of pages and abbreviated titles are displaying, but TOCs are still not displaying in the catalog.

**Comment by annakrohn** [comment]
All table of contents should now appear.
