### ISSUE TITLE
catalog new versions of Artistotle Ars Poetica

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#31]
In https://github.com/PerseusDL/canonical/pull/112, Stella is adding Greek and Arabic versions of Aristotle Ars Poetica to the Perseus canonical repo in order to make them available for editing in Perseids.

In order to facilitate this, she assigned the following version identifiers to them:

urn:cts:tlg0086.tlg034.digicorpus-ara1
urn:cts:tlg0086.tlg034.digicorpus-grc1

Interestingly, these texts come to us by way of us, from the joint Harvard/Tufts GrecoArabic corpus, which is now apparently published at http://digicorpus.net4media-typo3.de/

The source files for these are also here https://bitbucket.org/grecoarabiccorpus/opensourcetexts

I think if we are adding them to Perseids and the Perseus canonical repo, we should also have a catalog entry for them.  Not sure our process yet supports predefined version identifiers though.

**Comment by AlisonBabeu** [comment]
These files are now in catalog_pending and waiting the next ingest
https://github.com/PerseusDL/catalog_pending/tree/master/mods/Aristotle
