### ISSUE TITLE
errors in XML markup returned by GetCapabilities (user report)

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#32]
(please move if this is not a catalog data issue)

http://catalog.perseus.org/catalog/urn:cts:latinLit:phi1351
http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg7000

-------- Original Message --------
Subject:    GetCapabilities XML errors
Resent-From:    Perseus_Webmaster@tufts.edu
Date:   Sun, 30 Nov 2014 19:46:34 -0500
To:     Perseus DL Webmaster Perseus_Webmaster@tufts.edu

I have found the following errors in XML markup returned by GetCapabilities:
Textgroup latinLit:phi1351 groupname is coded as “C. Suetonius Tranquillus” but is actually Tacitus;
Textgroup greekLit:tlg7000 groupname is coded as “greekLit:tlg7000” but is actually Greek Anthology.

**Comment by AlisonBabeu** [comment]
The first issue involving Suetonius and Tacitus has been fixed, but the issue with the TLG identifier for the Greek Anthology will need further investigation.

**Comment by AlisonBabeu** [comment]
After further investigation, it seems that the assignment of the TLG ID 7000 to one anonymous epigram by Damostratus, which was also unfortunately encoded in the authority record, caused this issue, along with another issue of the Textgroup name being incorrect. I fixed the textgroup name, deleted the incorrect record, and created a new ID for Damostratus. I'm going to leave this issue open until the next update to see if that fixes the issue.

**Comment by AlisonBabeu** [comment]
This issue cannot be closed yet. The TLG 7000 for the Greek Anthology still has the linked author name of Damostratus and the textgroup still lists two incorrect related versions that have been deleted and redirected.

**Comment by AlisonBabeu** [comment]
I believe that this issue will only be fixed if the Greek Anthology Textgroup has its own authority record for the ID tlg7000. So I'm going to create one and put into catalog_pending.

**Comment by AlisonBabeu** [comment]
This issue will never be fixed in the legacy interface but it is fixed in the metadata so I"m closing this issue.
