### ISSUE TITLE
should merge tlg0060.tlg001.perseus-grc1 - tlg0060.tlg001.perseus-grc3 ?

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#37]
we currently have 3 separate versions for the Perseus edition of this work (Diodorus Siculus Historical Library)  tlg0060.tlg001.perseus-grc1 - tlg0060.tlg001.perseus-grc3 - but I think they are really only version right?

**Comment by AlisonBabeu** [comment]
Actually this is correct. There are two Greek editions of Diodorus Siculus on the Perseus website.
tlg0060.tlg001(https://github.com/PerseusDL/catalog_data/blob/e0dc08189a36e493f23f0c9044c5bea864ec9aad/mods/greekLit/tlg0060/tlg001/perseus-grc1/tlg0060.tlg001.perseus-grc1.mods1.xml) is for Books I-V of the Dindorf-Bekker edition (http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3atext%3a2008.01.0540) and tlg0060.tlg002 (https://github.com/PerseusDL/catalog_data/blob/e0dc08189a36e493f23f0c9044c5bea864ec9aad/mods/greekLit/tlg0060/tlg001/perseus-grc2/tlg0060.tlg001.perseus-grc2.mods1.xml) is for Books XVIII-XX of that edition (http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3atext%3a2008.01.0541). The last record tlg0060.tlg001.perseus-grc3 (https://github.com/PerseusDL/catalog_data/blob/e0dc08189a36e493f23f0c9044c5bea864ec9aad/mods/greekLit/tlg0060/tlg001/perseus-grc3/tlg0060.tlg001.perseus-grc3.mods1.xml)  is for the Oldfather-Loeb edition (http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3atext%3a1999.01.0083).

**Comment by balmas** [comment]
ah, okay thanks!
