### ISSUE TITLE
need MODS file for epidoc edition of urn:cts:phi1020.phi003

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#38]
I'm creating an epidoc edition of urn:cts:phi1020.phi003 (based on urn:cts:phi1020.phi003.perseus-grc1) for editing in Perseids.  We need a new MODS file for this.

**Comment by AlisonBabeu** [comment]
To clarify, there is no Greek version of this work, so I'm assuming an Epidoc edition MODS record needs to be created for: urn:cts:latinLit:phi1020.phi003.perseus-lat1?

**Comment by balmas** [comment]
yes, my bad

**Comment by AlisonBabeu** [comment]
No worries.

**Comment by AlisonBabeu** [comment]
I have created a MODS record and will push it out to catalog_pending when the updating is all done.

**Comment by AlisonBabeu** [comment]
This file has been created and is currently in catalog_pending.
https://github.com/PerseusDL/catalog_pending/blob/7ac838d70ff8ae6a3eae216de09d47e11e9cafa3/mods/Statius/Epidoc%20Editions/statius.Achilleis%28Perseus-Epidoc%29.mods.xml
