### ISSUE TITLE
new MODS files needed for Thuc translations

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#42]
@srdee has made (or will make) epidoc versions of the Perseus thuc translations (tlg0003.tlg001.perseus-eng1, tlg0003.tlg001.perseus-eng2 and tlg0003.tlg001.perseus-eng3). We need new MODS files for these versions so they can be assigned new URNs.

**Comment by AlisonBabeu** [comment]
I have created three MODS files for these soon to be created translation Epidoc files.
https://github.com/PerseusDL/catalog_pending/tree/master/mods/Thucydides

**Comment by balmas** [comment]
the following CTS urns are assumed for these in Perseids:

urn:cts:greekLit:tlg0003.tlg001.perseus-eng4
urn:cts:greekLit:tlg0003.tlg001.perseus-eng5
urn:cts:greekLit:tlg0003.tlg001.perseus-eng6

**Comment by balmas** [comment]
we also have new translations coming in from OGL, with the following URNS assumed
urn:cts:greekLit:tlg0003.tlg001.opp-ger1
urn:cts:greekLit:tlg0003.tlg001.opp-ger2
urn:cts:greekLit:tlg0003.tlg001.opp-ger3
urn:cts:greekLit:tlg0003.tlg001.opp-fre1

**Comment by AlisonBabeu** [comment]
I had created new MODS Epidoc records for the other new translations.

**Comment by AlisonBabeu** [comment]
All of these files now have permanent catalog records with working URNs so I am now closing this issue.
