### ISSUE TITLE
new MODs file for Plutarch Pericles

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#44]
I've created an Epidoc version of tlg0007.tlg0012.perseus-grc1, named provisionaly tlg0007.tlg0012.perseus-grc1, for inclusion in Perseids. We need it officially added to the catalog.

**Comment by balmas** [comment]
Also for the english, I've created an Epidoc version of tlg0007.tlg0012.perseus-eng1, named provisionally tlg0007.tlg0012.perseus-eng2, for inclusion in Perseids. We need it officially added to the catalog.

**Comment by AlisonBabeu** [comment]
I have created MODS records for these file and put them into catalog_pending, here: https://github.com/PerseusDL/catalog_pending/blob/master/mods/Plutarch/tlg007.tlg012.perseus-eng2.mods.xml and https://github.com/PerseusDL/catalog_pending/blob/master/mods/Plutarch/tlg007.tlg012.perseus-grc2.mods.xml

**Comment by AlisonBabeu** [comment]
These files both have permanent catalog records so I'm closing this issue.
