### ISSUE TITLE
System not using dates found in certain elements.

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/catalog_data#46]
The facet search http://catalog.perseus.org/?f[year_facet][]=0 revealed an interesting issue as to how the system seems to be pulling "Edition or Translation Year Published". 218 records have the year 0. In some cases, such as with the new Arabic records I think this has been caused by the presence of this in the MODS record:
In some cases the Arabic record  mods:dateIssued-/mods:dateIssued

Nonetheless, for some classical editions, I am wondering if it is failing to list a date due to different date encoding structures in the XML:

For example, http://data.perseus.org/catalog/urn:cts:latinLit:phi0134.phi004.opp-eng1/atom has the following date encoding:
mods:dateModified1900/mods:dateModified
mods:dateCreated1894/mods:dateCreated

and http://data.perseus.org/catalog/urn:cts:latinLit:phi0914.phi001.opp-eng4/atom has the following date encoding:
mods:copyrightDate1959/mods:copyrightDate
mods:dateModified1967/mods:dateModified

There don't seem to be any issues with records that have the following data encoding: dateIssued 
mods:dateIssued1878/mods:dateIssued

**Comment by annakrohn** [comment]
I've made it so it won't record '0' for dates anymore, if there isn't any date it just won't show up in the facet list.

I've also added capturing of dateCreated and copyrightDate.  Right now, it will just dump it into the existing date_publ field if it doesn't get a dateIssued. [Here](https://github.com/PerseusDL/perseus_catalog/commit/88187dfc613465e40a67678e714368eab8d95853) and [here](https://github.com/PerseusDL/perseus_catalog/commit/8e05871cc2421ec9b8175347d7adcfc3c9c7b74a).  If that is an issue, I can figure out a way to differentiate them in the display, but right now I just want to get a date of some sort for all editions.
