### ISSUE TITLE
Calpurnius Flaccus URN : request for a new edition level identifier

### ISSUE THREAD

**Issue by enury** [PerseusDL/catalog_data#47]
Bibliographic information for the phi edition of Calpurnius Flaccus' Declamations:
http://latin.packhum.org/author/1100

Author: Calpurnius Flaccus
Year: 1978
Title: Calpurnii Flacci declamationum excerpta / eddidit Lennart Håkanson
Publisher: Stuttgart, Teubner
Series: Bibliotheca scriptorum Graecorum et Romanorum Teubneriana
ISBN: 3519011301

Thanks!

**Comment by AlisonBabeu** [comment]
A catalog record ( https://github.com/PerseusDL/catalog_pending/blob/master/mods/Calpurnius%20Flaccus/CalpurniusFlaccus.Teubner%28Hakanson-1978%29.Declamationum.mods.xml) has been created for this file with a CTS-URN edition level identifier of urn:cts:latinLit:phi1100.phi001.opp-lat2.

**Comment by AlisonBabeu** [comment]
This work has been succesfully ingested into the catalog, http://catalog.perseus.org/catalog/urn:cts:latinLit:phi1100.phi001.opp-lat2 so I'm closing this issue.
