### ISSUE TITLE
MODS file for Homeric Hymn to Demeter

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#49]
@srdee in pull request https://github.com/PerseusDL/canonical/pull/137 created an epidoc version of urn:cts:greekLit:tlg0013.tlg002.perseus-grc1 as urn:cts:greekLit:tlg0013.tlg002.perseus-grc2.  We need to add this version to the catalog, via a MODS record..

**Comment by AlisonBabeu** [comment]
An Epidoc edition has been created for this file and is currently in catalog_pending: https://github.com/PerseusDL/catalog_pending/blob/master/mods/Homeric%20Hymns/tlg0013.tlg002.perseus-grc2.mods1.xml.

**Comment by AlisonBabeu** [comment]
This file has been successfully added to the catalog so I'm closing this issue.
