### ISSUE TITLE
None of the editions for an author display in the catalog

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/catalog_data#50]
For some reason none of the three works for the author Censorinus are displaying in the catalog. If you look at: http://catalog.perseus.org/catalog/urn:cts:latinLit:stoa0084.stoa001, http://catalog.perseus.org/catalog/urn:cts:latinLit:stoa0084.stoa002, or http://catalog.perseus.org/catalog/urn:cts:latinLit:stoa0084.stoa003. All of the metadata seems correct and the information is in the CITE Tables so I'm not sure what is going on. These records also do not contain an empty series element, which I know had caused this display issue in the past.

**Comment by annakrohn** [comment]
The fix will be live in the next update.
