### ISSUE TITLE
need new mods files for ovid, juvenal, martial

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#51]
@ PonteIneptique created cts-ized epidoc versions of ovid, martial, juvenal per https://github.com/PerseusDL/canonical/pull/148 
filenames are based upon expected new urns but we need mods files added to catalog data and new urns registered

**Comment by AlisonBabeu** [comment]
I just have one question, it appears that these file names, despite being Epidoc editions, are still based on the existing URNs. Wouldn't the new URNs and file names all have the endings perseus-lat2?

**Comment by balmas** [comment]
yes, sorry that was the old pull request. The correct one, with the new file names, is #149

**Comment by AlisonBabeu** [comment]
I have created MODS file for the various Ovid, Juvenal and Martial Epidoc editions and have pushed the files to catalog_pending
