### ISSUE TITLE
system did not seem to delete versions that were redirected

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/catalog_data#54]
While the latest import does seem to have ingested all of the Perseus editions, there has been an issue in that in many cases there were invalid/incorrect versions that have not been removed. For example, 
http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0062.tlg042.opp-grc1 was actually the Perseus edition. Although there is no longer a MODS file for this edition in the catalog_data repository and the URN was flagged as invalid and redirected in the CITE Collections table this does not seem to have been captured in the latest update. Having checked on a number of Perseus editions where OPP editions MODS files were deleted and the URNS were flagged as invalid and redirected (for example, http://catalog.perseus.org/cite-collections/versions/urn:cite:perseus:catver.5254.1) it does not appear that any of the redirected URNs and invalid versions were removed.

**Comment by balmas** [comment]
I believe this is because, as currently coded, we need to do a full reload of the catalog database each time, dropping the current data before running the parse_records task.

**Comment by balmas** [comment]
But, we also still need to figure out how we want to handle redirections of previously published urns.  It's my feeling that these should not be included in the Blacklight Catalog interface, but that the resolver for http://data.perseus.org/ urls should check the redirect_to value in the cite collection tables to send people to the right version.

**Comment by AlisonBabeu** [comment]
That sounds like a good plan to me!

**Comment by balmas** [comment]
closing this. See https://github.com/PerseusDL/cite_collections_rails/issues/20
