### ISSUE TITLE
urn:cts:latinLit:phi1017.phi011.perseus-eng1 is not in the catalog

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/catalog_data#62]
Could it be registered under some other name ?

**Comment by AlisonBabeu** [comment]
After looking it appears I might have missed this one in my cataloging sweep. I'll take a further look and if not I will create a MODS record for it. Oops.

**Comment by AlisonBabeu** [comment]
So a catalog record has been created for this and is now in catalog_pending. https://github.com/PerseusDL/catalog_pending/blob/master/mods/Seneca%20the%20Younger/2007.01.0029.mods.xml

**Comment by AlisonBabeu** [comment]
This work is now in the catalog so I'm closing this issue.
