### ISSUE TITLE
Eustathius' Ad Iliadem and Ad Odysseam have no URN

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/catalog_data#63]
Today I encountered [Eustathius](http://catalog.perseus.org/catalog/urn:cite:perseus:author.604) "Ad Iliadem" and "Ad Odysseam" in Perseus [Apollodorus Epitom translation notes of the editor](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0022%3Atext%3DEpitome%3Abook%3DE%3Achapter%3D5%3Asection%3D13) as well as [Smith's Diomede entry](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0104%3Aalphabetic+letter%3DD%3Aentry+group%3D11%3Aentry%3Ddiomedes-bio-1)

Archives.org links : 
- https://archive.org/details/commentariiadho02eust
- https://archive.org/details/commentariiadhom01eust

**Comment by AlisonBabeu** [comment]
Thankfully these works do have TLG so they have easy URNs:
"Ad Iliadem" is tlg4083.tlg002 
"Ad Odysseam" is tlg4083.tlg003
Or is more information needed?

**Comment by PonteIneptique** [comment]
Not at all, I was just opening for the catalog to receive potentially new data as I encountered the rare situation of not finding a work on it :)

**Comment by AlisonBabeu** [comment]
This is resolved so I'm closing this issue.

**Comment by lcerrato** [comment]
@AlisonBabeu tlg4083.tlg001 is the Commentary on the Iliad we have mapped elsewhere. See: 
https://github.com/PerseusDL/lexica/issues/59
