### ISSUE TITLE
urn:cts:latinLit:stoa0089.stoa007.perseus-lat1

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/catalog_data#65]
There is no records for http://catalog.perseus.org/catalog/urn:cts:latinLit:stoa0089.stoa007.perseus-lat1

**Comment by AlisonBabeu** [comment]
In the first automatic creation of data records for the Perseus catalog, the MODS record for this was missed, so I've put it into catalog_pending,  https://github.com/PerseusDL/catalog_pending/blob/master/mods/Claudian%20/stoa0089.stoa007.perseus-lat1.mods.xml.

**Comment by AlisonBabeu** [comment]
This file is now in the catalog so I"m closing this issue.
