### ISSUE TITLE
should tlg0003.tlg001.opp-ger2 and tlg0003.tlg001.opp-ger3 be merged?

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#69]
@AlisonBabeu you created 2 mods files for opp-ger1 and opp-ger2 (via issue #42) but it looks to me like this maybe should have been a modsCollection for a single multi-volume work (and that these 2 files should thus merged). Is that correct?

**Comment by AlisonBabeu** [comment]
They should be a modsCollection, we simply didn't have a process in place for multivolume editions when I created these MODS records and I didn't merge these records as yet because I wasn't sure if the individual URNs were important to preserve.

**Comment by balmas** [comment]
I think we should merge them both to opp-grc2.  @monberti and @gregorycrane do either of you have any opinion on this?  separate urns were created for each volume the German OPP T. Braun edition of Thuc when there should have been just one.  Both have been available in Perseids but I don't think much work has been done with them, so my preference would be to just merge them both into the first urn (tlg0003.tlg001.opp-ger2) and redirect the 2nd (tlg0003.tlg001.opp-ger3) to the first (opp-ger2).  The other option would be to retire both of these URNs and create a new one (i.e. tlg0003.tlg001.opp-ger4) that they both redirect to.

**Comment by balmas** [comment]
On the text side, I've gone ahead and merged opp-ger2 and opp-ger3 into opp-ger2.

**Comment by AlisonBabeu** [comment]
REsolved by last update
