### ISSUE TITLE
Number of erroneous duplicate textgroups created by July update need to be deleted

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/catalog_data#72]
Cato—stoa0079
Varro —stoa0286
Ovid—stoa0216
Horace— stoa0152
Pliny —stoa0232-stoa001

The versions created under these textgroups IDs need to be deleted, their URNs redirected, and the files put back into catalog_pending for reingest at the next update.

**Comment by balmas** [comment]
this is the list of stoa works added by the import in July 2015:

urn:cts:latinLit:stoa0079.stoa001  
urn:cts:latinLit:stoa0286.stoa004  
urn:cts:latinLit:stoa0258.stoa028  
urn:cts:latinLit:stoa0067.stoa001  
urn:cts:latinLit:stoa0152.stoa006  
urn:cts:latinLit:stoa0071b.stoa001 
urn:cts:latinLit:stoa0021a.stoa001
urn:cts:latinLit:stoa0216.stoa005  
urn:cts:latinLit:stoa0216.stoa013 
urn:cts:latinLit:stoa0216.stoa004  
urn:cts:latinLit:stoa0216.stoa008 
urn:cts:latinLit:stoa0216.stoa006  
urn:cts:latinLit:stoa0087.stoa061

**Comment by AlisonBabeu** [comment]
Thanks for the list!

**Comment by AlisonBabeu** [comment]
urn:cts:latinLit:stoa0259.stoa002 is another one to delete is appears as well.

**Comment by AlisonBabeu** [comment]
I've deleted all these erroneous textgroups and redirected the files in the CiteCollection tables.

**Comment by AlisonBabeu** [comment]
I've reopened this issue because even though all of the versions appear to have correctly redirected and are appearing under the authors top level PHI ID, there are still records in the catalog for these textgroups such as http://107.23.45.22:3000/catalog/urn:cts:latinLit:stoa0216.stoa005. Once a textgroup has been created, do I need to redirect it in the Textgroup Cite Collection tables as well as redirect all the versions? Such as redirecting http://catalog.perseus.org/cite-collections/textgroups/urn:cite:perseus:cattg.1920.1 to http://catalog.perseus.org/cite-collections/textgroups/urn:cite:perseus:cattg.1307.1.

**Comment by balmas** [comment]
hmm. yes I think so.  There is a redirect_to field in that table.

**Comment by AlisonBabeu** [comment]
What I'm doing now, thanks for your insanely instantaneous feedback.

**Comment by balmas** [comment]
Closing this. Fixed data should be in https://github.com/PerseusDL/catalog_data/releases/tag/20160418

**Comment by AlisonBabeu** [comment]
So while it looks like the data has been fixed, the online interface is still showing these textgroups
http://catalog.perseus.org/catalog/urn:cts:latinLit:stoa0152, although all of the versions underneath do not link to anything.

**Comment by balmas** [comment]
were they redirected in the cite collections?

**Comment by AlisonBabeu** [comment]
Yes, such as for Horace here, http://catalog.perseus.org/cite-collections/textgroups/urn:cite:perseus:cattg.1910.1

**Comment by balmas** [comment]
Ok. Will investigate.

**Comment by balmas** [comment]
See https://github.com/PerseusDL/perseus_catalog/issues/57 

Recommend closing this issue on the data. Requires code fix and another update before data correction takes effect in UI.
