### ISSUE TITLE
alternative title: phi0474.phi009.perseus-eng1.xml

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#77]
Of all the alternative titles, the one actually used in the translation isn't in the record. :(

In Defense of the Proposed Manilian Law

**Comment by AlisonBabeu** [comment]
I added in this alternative title to the record at https://github.com/PerseusDL/catalog_data/blob/master/mods/latinLit/phi0474/phi009/perseus-eng1/phi0474.phi009.perseus-eng1.mods1.xml.

**Comment by balmas** [comment]
Live wtih https://github.com/PerseusDL/catalog_data/releases/tag/20160418
