### ISSUE TITLE
(tlg0540.tlg008.perseus-grc1) minor typo

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#94]
http://data.perseus.org/catalog/urn:cts:greekLit:tlg0540.tlg008.perseus-grc1/atom
`<mods:titleInfo type="translated" lang="eng">`
`<mods:title>`Accuastion of Calumny`</mods:title>`

**Comment by AlisonBabeu** [comment]
Thanks for catching this, its been fixed!
