### ISSUE TITLE
urn:cts:greekLit:tlg5019 scholia to two different "Dionysius" grouped together

### ISSUE THREAD

**Issue by ChiaraPalladino** [PerseusDL/catalog_data#95]
The entry refers to scholia to the work of two different authors: 

Dionysius of Byzantium, De Bosphori Navigatione (urn:cts:greekLit:tlg0083.tlg003) 
Dionysius Periegetes, Orbis Descriptio (urn:cts:greekLit:tlg0084.tlg001)

But the current works cataloged concern the Periegetes only: 
urn:cts:greekLit:tlg5019.tlg002 (Ludwich Edition, correct) 
urn:cts:greekLit:tlg5019.tlg001: Scholia vetera, Mueller (with Latin translation) and Bernhardy edition, both on Dionysius Periegetes **but here wrongly classified as Scholia in Dionysium Byzantium**, who's a different person. 

The Scholia to Dionysius Byzantius, also called recentiora, were published by Guengerich in 1958 (R. Güngerich, Dionysii Byzantii anaplus Bospori una cum scholiis x saeculi, 2nd edn., Berlin: Weidmann, 1958: 36-40) and are absent from the Catalog.

**Comment by AlisonBabeu** [comment]
Thanks @ChiaraPalladino for catching this as well. For some reasons the records under  urn:cts:greekLit:tlg5019.tlg001 had the incorrect author and work title, despite being Scholia on Dionysius Periegetes. I have fixed this in the records on catalog_data and it will be reflected online the next time the catalog is updated.
