### ISSUE TITLE
urn:cts:latinLit:stoa0111.stoa001.opp-lat2  wrong title

### ISSUE THREAD

**Issue by ChiaraPalladino** [PerseusDL/catalog_data#96]
It's not the Itinerarium Egeriae, but a poem attributed to one Eucheria. 

I couldn't find anything on the poetess, but it shouldn't be the same person, judging from geographical and social origin. See [this note 
](https://books.google.com/books?id=krcp3GU2MssC&pg=PA37&lpg=PA37&dq=aurea+concordi+quae+fulgent&source=bl&ots=DpY6Q5ZAL3&sig=d8rb7XO-t7fGLAnG4p-NpXkvpXc&hl=it&sa=X&ved=0ahUKEwjJ4Kq7_YvUAhVB6YMKHTiJBUsQ6AEIOTAE#v=onepage&q=aurea%20concordi%20quae%20fulgent&f=false) in Mathisen vol. 2. 

See, it doesn't always have to be a Dionysius...

**Comment by AlisonBabeu** [comment]
@ChiaraPalladino you are quite right not only is this the wrong title this work is by an entirely different author, I believe the author is this Eucheria found here in VIAF (http://viaf.org/viaf/34811444/#) and she also has an entry in Brill. I will delete this entry, and create a new authority record and ID for this work. Thanks so much for catching this.
